Repository Android-Guild/Picover, pull requests merged in 2023-10, with the labels that each got.

#317 #316 Fix large stack of destinations
  app/src/main/kotlin/com/intive/picover/main/view/MainActivity.kt
Labels: bug

#271 #119 manage new party
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/intive/picover/common/text/PicoverOutlinedTextField.kt
  app/src/main/kotlin/com/intive/picover/parties/view/PartiesScreen.kt
  app/src/main/kotlin/com/intive/picover/parties/view/PartyBottomSheet.kt
  app/src/main/kotlin/com/intive/picover/parties/viewmodel/PartiesViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/intive/picover/parties/viewmodel/PartiesViewModelTest.kt
Labels: enhancement

#344 #343 Agreements section in ReadMe and text validation
  README.md
Labels: documentation
