Repository Android-Guild/Picover, pull requests merged in 2023-09, with the labels that each got.

#182 #165 Bump kotlin and compose compiler
  app/build.gradle.kts
  gradle/libs.versions.toml
  lint/build.gradle.kts
Labels: dependencies

#183 #165 Migrate dagger to ksp
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#188 #184 Update PR info in ReadMe
  README.md
Labels: documentation

#192 #170 If the user is not logged in we get NPE
  app/src/main/kotlin/com/intive/picover/auth/repository/AuthRepository.kt
  app/src/test/kotlin/com/intive/picover/auth/repository/AuthRepositoryTest.kt
Labels: bug

#261 #260 validator update for Short and Long tex
  app/src/main/kotlin/com/intive/picover/common/di/AppModule.kt
  app/src/main/kotlin/com/intive/picover/common/validator/qualifier/Validator.kt
  app/src/main/kotlin/com/intive/picover/profile/di/ProfileModule.kt
  app/src/main/kotlin/com/intive/picover/profile/viewmodel/ProfileViewModel.kt
Labels: enhancement
